local_costmap:
  global_frame: odom
  update_frequency: 1.0
  publish_frequency: 1.0
  transform_tolerance: 0.2
  static_map: false
  rolling_window: true
  resolution: 0.05
  inflation_radius: 0.1
  # plugins:
  #   - { name: obstacle_layer, type: "costmap_2d::ObstacleLayer" }

  # obstacle_layer:
  #   observation_sources: laser_scan_sensor
  #   laser_scan_sensor:
  #     {
  #       sensor_frame: laser,
  #       data_type: LaserScan,
  #       topic: scan,
  #       marking: true,
  #       clearing: true,
  #     }
