#INCLUDE<TV_16F887.C>
#INCLUDE<TV_KEY4X3.C>
SIGNED INT16 MP, NUMBER;
VOID MAIN()
{
SET_TRIS_A(0xFF); //SET PORT A TO BE INPUT PORT
SET_TRIS_B(0xFF); // INPUT PORT
SET_TRIS_C(0X00); //OUTPUT PORT
NUMBER = 0x83; // BAN DAU HIEN CHU b
OUTPUT_C(NUMBER);
WHILE(TRUE)
   {

   MP= KEY_4X3();
   IF (MP!=0XFF)
      {
      NUMBER=MA7DOAN_4X3[MP];
      OUTPUT_C(NUMBER);
      }
   }
}
