#INCLUDE<TV_16F887.C>
#INCLUDE<TV_KEY4X4.C>
SIGNED INT16 MP;
VOID MAIN()
{
SET_TRIS_D(0x00); OUTPUT_D(0x7F);
SET_TRIS_B(0xF0); PORT_B_PULLUPS(0XF0);
WHILE(TRUE)
{
MP= KEY_4X4();
IF (MP!=0XFF)
{
OUTPUT_D(MA7DOAN[MP]);
}
}
}
