#INCLUDE <TV_16F887.C>
#INCLUDE<TV_LCD.C>
UNSIGNED INT16 TIME, DEM;
VOID LCD_HIENTHI()
{
   LCD_COMMAND(ADDR_LINE1); 
   LCD_DATA((TIME/1000)+0X30);
   LCD_DATA((TIME/100)%10+0X30);
   LCD_DATA((TIME/10)%10+0X30);
   LCD_DATA((TIME%10)+0X30);
  
}
}
VOID MAIN()
{
   DEM=0;
   SETUP_TIMER_0(T0_EXT_L_TO_H | T0_DIV_1);
   SET_TIMER0(0);
   WHILE(TRUE)
   {
   SET_TRIS_E(0x00); SET_TRIS_D(0x00);
   LCD_SETUP();
   LCD_HIENTHI();
   DELAY_MS(100);
   DEM = GET_TIMER0();
   IF (DEM == 1) 
   {
      SET_TIMER0(0);TIME ++;

      IF(TIME == 1000) TIME = 0;  
   }
   }
}
