#INCLUDE <TV_16F887.C>
#INCLUDE<TV_LCD.C>
UNSIGNED INT16 KQADC;
VOID LCD_HIENTHI()
{
   LCD_COMMAND(ADDR_LINE1); 
   LCD_DATA((KQADC/1000)+0X30);
   LCD_DATA((KQADC/100)%10+0X30);
   LCD_DATA((KQADC/10)%10+0X30);
   LCD_DATA((KQADC%10)+0X30);
  
}
VOID MAIN()
{
   SETUP_ADC(ADC_CLOCK_DIV_8);
   SETUP_ADC_PORTS(SAN0);

   WHILE(TRUE)
   {
   LCD_SETUP();
   SET_TRIS_E(0x00); SET_TRIS_D(0x00);
   SETUP_ADC(ADC_CLOCK_DIV_8);
   SET_ADC_CHANNEL(0);
   KQADC=READ_ADC();
   DELAY_MS(1);
   KQADC= KQADC /2.046;
   LCD_HIENTHI();
   DELAY_MS(1000);
   
   
   }
}
