#INCLUDE <TV_16F887.C>
#INCLUDE <TV_LCD.C>
VOID MAIN()
{
SET_TRIS_E(0x00);
SET_TRIS_D(0x00);
LCD_SETUP();
LCD_COMMAND(ADDR_LINE1); DELAY_US(10);
LCD_DATA("THU7 PHAI DI HOC");
LCD_COMMAND(ADDR_LINE2); DELAY_US(10);
LCD_DATA("DITMECUOCDOI");
while(TRUE) {}
}
